// Generated by scripts/build-search-index.mjs. Do not edit.
export interface SearchEntry {
  href: string
  title: string
  section: string | null
  text: string
}

export const SEARCH_INDEX: SearchEntry[] = [
  {
    "href": "/docs",
    "title": "Getting started",
    "section": null,
    "text": "Yöte is a small set of form inputs for React, styled and animated out of the box, with one prop vocabulary shared by every field. Zero dependencies."
  },
  {
    "href": "/docs/accessibility",
    "title": "Accessibility",
    "section": null,
    "text": "What every Yöte field does without being asked. None of it is opt-in."
  },
  {
    "href": "/docs/accessibility#dropdowns",
    "title": "Accessibility",
    "section": "Dropdowns",
    "text": ""
  },
  {
    "href": "/docs/accessibility#input",
    "title": "Accessibility",
    "section": "Input behaviour",
    "text": ""
  },
  {
    "href": "/docs/accessibility#labelling",
    "title": "Accessibility",
    "section": "Labelling",
    "text": ""
  },
  {
    "href": "/docs/accessibility#masked",
    "title": "Accessibility",
    "section": "Masked fields",
    "text": ""
  },
  {
    "href": "/docs/accessibility#messages",
    "title": "Accessibility",
    "section": "Messages",
    "text": ""
  },
  {
    "href": "/docs/accessibility#motion",
    "title": "Accessibility",
    "section": "Motion",
    "text": ""
  },
  {
    "href": "/docs/accessibility#tags",
    "title": "Accessibility",
    "section": "Tags",
    "text": ""
  },
  {
    "href": "/docs/card",
    "title": "Card number",
    "section": null,
    "text": "A card number that regroups itself as it recognises the card, and a mark that changes with it. It does not tell you whether the number is real."
  },
  {
    "href": "/docs/card#grouping",
    "title": "Card number",
    "section": "Grouping follows the brand",
    "text": ""
  },
  {
    "href": "/docs/card#mark",
    "title": "Card number",
    "section": "The mark is on the left",
    "text": ""
  },
  {
    "href": "/docs/card#props",
    "title": "Card number",
    "section": "Props",
    "text": ""
  },
  {
    "href": "/docs/card#validation",
    "title": "Card number",
    "section": "No Luhn check",
    "text": ""
  },
  {
    "href": "/docs/date",
    "title": "Date",
    "section": null,
    "text": "A date typed, not picked. The field types the punctuation for you, takes a paste of whatever shape, and never tells you whether the date is real."
  },
  {
    "href": "/docs/date#no-picker",
    "title": "Date",
    "section": "There is no calendar",
    "text": ""
  },
  {
    "href": "/docs/date#pattern",
    "title": "Date",
    "section": "Pattern",
    "text": ""
  },
  {
    "href": "/docs/date#props",
    "title": "Date",
    "section": "Props",
    "text": ""
  },
  {
    "href": "/docs/date#value",
    "title": "Date",
    "section": "What you get back",
    "text": ""
  },
  {
    "href": "/docs/digit-input",
    "title": "Digit input",
    "section": null,
    "text": "A one-time code field. Type in it: the pills seed a state, but the component underneath is the real thing."
  },
  {
    "href": "/docs/digit-input#anatomy",
    "title": "Digit input",
    "section": "One input, not one per cell",
    "text": ""
  },
  {
    "href": "/docs/digit-input#errors",
    "title": "Digit input",
    "section": "Errors",
    "text": ""
  },
  {
    "href": "/docs/digit-input#props",
    "title": "Digit input",
    "section": "Props",
    "text": ""
  },
  {
    "href": "/docs/digit-input#state-attributes",
    "title": "Digit input",
    "section": "State attributes",
    "text": ""
  },
  {
    "href": "/docs/input",
    "title": "Text input",
    "section": null,
    "text": "One line of text, with room at either end for a mark or an affix. The plainest field in the library, and the one the others are shaped like."
  },
  {
    "href": "/docs/input#props",
    "title": "Text input",
    "section": "Props",
    "text": ""
  },
  {
    "href": "/docs/input#sizes",
    "title": "Text input",
    "section": "Sizes",
    "text": ""
  },
  {
    "href": "/docs/input#slots",
    "title": "Text input",
    "section": "Slots",
    "text": ""
  },
  {
    "href": "/docs/password",
    "title": "Password",
    "section": null,
    "text": "Masked entry with a reveal toggle, and a requirements block that reports which rules a password meets as it is typed."
  },
  {
    "href": "/docs/password#accessibility",
    "title": "Password",
    "section": "Accessibility",
    "text": ""
  },
  {
    "href": "/docs/password#props",
    "title": "Password",
    "section": "Props",
    "text": ""
  },
  {
    "href": "/docs/password#requirements",
    "title": "Password",
    "section": "Requirements",
    "text": ""
  },
  {
    "href": "/docs/password#strength",
    "title": "Password",
    "section": "Strength",
    "text": ""
  },
  {
    "href": "/docs/phone",
    "title": "Phone number",
    "section": null,
    "text": "A dialling country and a national number in one field. The country and the number are separate values, because storing them joined is a decision you should make, not one the field makes for you."
  },
  {
    "href": "/docs/phone#countries",
    "title": "Phone number",
    "section": "Countries",
    "text": ""
  },
  {
    "href": "/docs/phone#flags",
    "title": "Phone number",
    "section": "Flags",
    "text": ""
  },
  {
    "href": "/docs/phone#picker",
    "title": "Phone number",
    "section": "The picker",
    "text": ""
  },
  {
    "href": "/docs/phone#props",
    "title": "Phone number",
    "section": "Props",
    "text": ""
  },
  {
    "href": "/docs/phone#sizes",
    "title": "Phone number",
    "section": "Sizes",
    "text": ""
  },
  {
    "href": "/docs/phone#values",
    "title": "Phone number",
    "section": "Two values",
    "text": ""
  },
  {
    "href": "/docs/select",
    "title": "Select",
    "section": null,
    "text": "Two shapes of the same idea. SelectInput is a field whose own text is the search. InlineSelect is a small one that lives inside another field."
  },
  {
    "href": "/docs/select#inline",
    "title": "Select",
    "section": "Inline selector",
    "text": ""
  },
  {
    "href": "/docs/select#inline-props",
    "title": "Select",
    "section": "InlineSelect props",
    "text": ""
  },
  {
    "href": "/docs/select#keyboard",
    "title": "Select",
    "section": "Keyboard",
    "text": ""
  },
  {
    "href": "/docs/select#props",
    "title": "Select",
    "section": "SelectInput props",
    "text": ""
  },
  {
    "href": "/docs/select#search",
    "title": "Select",
    "section": "The field is the search",
    "text": ""
  },
  {
    "href": "/docs/styling",
    "title": "Styling",
    "section": null,
    "text": "Yöte ships plain CSS inside a cascade layer. There is no Tailwind in the package and no config to inherit."
  },
  {
    "href": "/docs/styling#layer-order",
    "title": "Styling",
    "section": "Layer order",
    "text": ""
  },
  {
    "href": "/docs/styling#per-part",
    "title": "Styling",
    "section": "Per-part classes",
    "text": ""
  },
  {
    "href": "/docs/styling#tokens",
    "title": "Styling",
    "section": "Tokens",
    "text": ""
  },
  {
    "href": "/docs/tags",
    "title": "Tags",
    "section": null,
    "text": "A field that collects a list. Type, press Enter, and the text becomes a tag you can remove."
  },
  {
    "href": "/docs/tags#editing",
    "title": "Tags",
    "section": "Adding and removing",
    "text": ""
  },
  {
    "href": "/docs/tags#placement",
    "title": "Tags",
    "section": "Two placements",
    "text": ""
  },
  {
    "href": "/docs/tags#props",
    "title": "Tags",
    "section": "Props",
    "text": ""
  },
  {
    "href": "/docs/textarea",
    "title": "Text area",
    "section": null,
    "text": "Multi-line entry, with an optional character counter and a drag handle. Hover the field to see the hover state. It is a real pointer state, not a pill."
  },
  {
    "href": "/docs/textarea#custom-properties",
    "title": "Text area",
    "section": "Custom properties",
    "text": ""
  },
  {
    "href": "/docs/textarea#props",
    "title": "Text area",
    "section": "Props",
    "text": ""
  },
  {
    "href": "/docs/textarea#resizing",
    "title": "Text area",
    "section": "Resizing",
    "text": ""
  },
  {
    "href": "/docs/textarea#sizes",
    "title": "Text area",
    "section": "Sizes",
    "text": ""
  },
  {
    "href": "/docs#components",
    "title": "Getting started",
    "section": "Components",
    "text": ""
  },
  {
    "href": "/docs#founder",
    "title": "Getting started",
    "section": "A message from the founder",
    "text": ""
  },
  {
    "href": "/docs#installation",
    "title": "Getting started",
    "section": "Installation",
    "text": ""
  },
  {
    "href": "/docs#scope",
    "title": "Getting started",
    "section": "Scope",
    "text": ""
  },
  {
    "href": "/docs#usage",
    "title": "Getting started",
    "section": "Usage",
    "text": ""
  }
]
